In [54]:
import pandas as pd
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cross_validation import train_test_split
from imutils import paths
import numpy as np
import argparse
import imutils
import matplotlib.image as mpimg


lego_pictures/pic_002.JPG


Preprocessing: Resizing and saving images

for file in os.listdir("lego_pictures"):
    img = cv2.imread("lego_pictures/"+file)
    small = cv2.resize(img, (32,32))

    cv2.imwrite('resized_pictures/resized_'+file, small)


Flattening images and adding values to an array

In [82]:
label_df = pd.read_csv('legos.csv')
df = pd.DataFrame([])
print(label_df['type'])

0      1x2-Block
1      1x2-Block
2      1x2-Block
3      1x2-Block
4      1x2-Block
5      1x2-Block
6      1x2-Block
7      1x2-Block
8      1x2-Block
9      1x2-Block
10     1x2-Block
11     1x2-Block
12     1x2-Block
13     1x2-Block
14     1x2-Block
15     1x2-Block
16     1x2-Block
17     1x2-Block
18     1x2-Block
19     1x2-Block
20     1x2-Block
21     1x2-Block
22     1x2-Block
23     1x2-Block
24     1x2-Block
25     1x2-Block
26     1x2-Block
27     1x2-Block
28     1x2-Block
29     1x2-Block
         ...    
570    1x1-Round
571    1x1-Round
572    1x1-Round
573    1x1-Round
574    1x1-Round
575    1x1-Round
576    1x1-Round
577    1x1-Round
578    1x1-Round
579    1x1-Round
580    1x1-Round
581    1x1-Round
582    1x1-Round
583    1x1-Round
584    1x1-Round
585    1x1-Round
586    1x1-Round
587    1x1-Round
588    1x1-Round
589    1x1-Round
590    1x1-Round
591    1x1-Round
592    1x1-Round
593    1x1-Round
594    1x1-Round
595    1x1-Round
596    1x1-Round
597    1x1-Rou

In [80]:
flat = list()
for file in os.listdir("resized_pictures"): 
    img = cv2.imread("resized_pictures/"+ file)
    flat.append(img.flatten())
flat

[array([165, 135, 140, ..., 104, 116, 128], dtype=uint8),
 array([160, 174, 193, ..., 139, 157, 174], dtype=uint8),
 array([109, 125, 142, ..., 113, 120, 123], dtype=uint8),
 array([138, 120, 137, ..., 119, 112, 127], dtype=uint8),
 array([122, 143, 145, ..., 225, 190, 176], dtype=uint8),
 array([120, 152, 158, ..., 247, 227, 210], dtype=uint8),
 array([47, 42, 43, ..., 37, 32, 34], dtype=uint8),
 array([13,  9, 14, ..., 42, 35, 32], dtype=uint8),
 array([23, 25, 26, ..., 48, 35, 33], dtype=uint8),
 array([51, 40, 26, ..., 53, 50, 46], dtype=uint8),
 array([62, 50, 48, ..., 73, 56, 47], dtype=uint8),
 array([74, 66, 66, ..., 44, 35, 38], dtype=uint8),
 array([183, 184, 198, ..., 157, 171, 190], dtype=uint8),
 array([174, 174, 180, ..., 180, 193, 191], dtype=uint8),
 array([152, 161, 170, ..., 224, 232, 221], dtype=uint8),
 array([138, 142, 153, ..., 167, 174, 167], dtype=uint8),
 array([170, 162, 179, ..., 193, 192, 194], dtype=uint8),
 array([148, 156, 173, ..., 157, 159, 159], dtype=

In [89]:
histogram = list()
bins = (8,8,8)
for file in os.listdir("lego_pictures"):
    img = cv2.imread("lego_pictures/"+file)
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    hist = cv2.calcHist([hsv], [0, 1, 2], None, bins,
    [0, 180, 0, 256, 0, 256])
    if imutils.is_cv2():
        hist = cv2.normalize(hist)
    else:
        cv2.normalize(hist, hist)
    histogram.append(hist.flatten())


In [90]:
histogram

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
